# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.GithubRepoStarsCountPlugin}}
plugins:

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "RamenFerno"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "RamenFernoüçúüî•"

# Tagline section text
tagline: >-
    VTuber, ramen chef, and fire hazard for your mind. I stream obscure indie games, blast wild tunes, and get possessed live by a fire daemon named Cal. The broth is boiling. All that's left is for you to join the other Embers!
    
    <iframe
        src="https://player.twitch.tv/?channel=ramenferno&parent=www.ramenferno.com"
        height="300"
        width="100%"
        allowfullscreen>
    </iframe>

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-twitch"
      text: "Twitch <span class='link-button-text'>(Streams start Fri-Sun at 10PM PST)</span>"
      url: "https://twitch.tv/RamenFerno"
      alt: "RamenFerno Twitch Channel"
      title: "RamenFerno Twitch Channel"
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      text: "YouTube <span class='link-button-text'>(Stream Highlights!)</span>"
      url: "https://www.youtube.com/@RamenFerno"
      alt: "RamenFerno YouTube Channel"
      title: "RamenFerno YouTube Channel"
      target: "_blank"
  - link:
      icon: "fa-brands fa-tiktok"
      text: "TikTok <span class='link-button-text'>(Stream Highlights!)</span>"
      url: "https://www.tiktok.com/@ramenferno"
      alt: "RamenFerno TikTok Page"
      title: "RamenFerno TikTok Page"
      target: "_blank"
  - link:
      icon: "fa-brands fa-discord"
      text: "Discord <span class='link-button-text'>(Join the Emberpot!)</span>"
      url: "https://discord.gg/HrmQAEdTcV"
      alt: "Emberpot Discord Server"
      title: "Emberpot Discord Server"
      target: "_blank"
  - link:
      icon: "fa-brands fa-twitter"
      text: "Twitter <span class='link-button-text'>(üê•)</span>"
      url: "https://twitter.com/@ramenferno"
      alt: "RamenFerno Twitter Page"
      title: "RamenFerno Twitter Page"
      target: "_blank"
  - link:
      icon: "fa-brands fa-bluesky"
      text: "Bluesky"
      url: "https://bsky.app/profile/ramenferno.com"
      alt: "RamenFerno Bluesky Page"
      title: "RamenFerno Bluesky Page"
      target: "_blank"
  - link:
      icon: "fa-classic fa-gift"
      text: "Throne <span class='link-button-text'>(Thank you so much!)</span>"
      url: "https://throne.com/ramenferno"
      alt: "RamenFerno's Throne Wishlist"
      title: "RamenFerno's Throne Wishlist"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/RamenFerno"
      title: "RamenFerno GitHub Page"
      alt: "RamenFerno GitHub Page"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/ramenferno"
      title: "RamenFerno Instagram Page"
      alt: "RamenFerno Instagram Page"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:ramenferno@outlook.com"
      title: "Email: ramenferno@outlook.com"
      alt: "ramenferno@outlook.com"
      target: "_blank"

# Footer text
footer: >
    <div style="margin-top:2em;text-align:center">
        <h3><b>Art Credits</b></h3>
        [Naraaa](https://vgen.co/naraaastudio)
        [Ferno model](https://vgen.co/naraaastudio/portfolio/showcase/ramenferno-s-live2d-model/43047066-5386-49c3-8058-f45494d04ff1)
        Emberpot model

        [Patt](https://vgen.co/patheaple)
        <i>Signal Flare</i> cover art
        [VTuber Base](https://vgen.co/patheaple/product/vtuber-base-body-model-rendered-not-rigged-/91ac2484-fa75-494f-8add-6670d099566f) (used for concept art)
        
        [Eruru](https://vgen.co/Eruru)
        [Flaming Bowl logo](https://vgen.co/Eruru/service/neon-sign-signature-watermark/a491f9ee-b519-4be5-8f86-2da7253b54ac)

        [milaeshop](https://www.etsy.com/shop/milaeshop)
        [Glowy chat widget](https://www.etsy.com/listing/4391673194/glowy-chat-widget-horizontal-and)
        
        [Shisma](https://commons.wikimedia.org/wiki/User:Shisma)
        [Japanese Wave Pattern](https://commons.wikimedia.org/wiki/File:Japanese_Wave_Pattern.svg) ([License](https://creativecommons.org/licenses/by-sa/4.0/))
    </div>

# Footer copyright message
# Linkyee is a 100% free, open-source project‚Äîfeel free to modify the copyright message as you like. :)
copyright: >
  Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
