# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.GithubRepoStarsCountPlugin}}
plugins:

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "RamenFerno"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "RamenFernoüçúüî•"

# Tagline section text
tagline: >-
    VTuber, ramen chef, and fire hazard for your mind. I stream obscure indie games, blast wild tunes, and get possessed live by a fire daemon named Cal. The broth is boiling. All that's left is for you to join the other Embers!
          
twitch_embed: >
    <div class="twitch-embed" style="margin-top:1em;text-align:center;">
        <iframe
          src="https://player.twitch.tv/?channel=ramenferno&parent=www.ramenferno.com"
          height="300"
          width="100%"
          allowfullscreen
          style="border-radius:12px;max-width:600px;">
        </iframe>
    </div>

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-youtube"
      text: "YouTube <span class='link-button-text'>(Stream Highlights!)</span>"
      url: "https://www.youtube.com/@RamenFerno"
      alt: "RamenFerno YouTube Channel"
      title: "RamenFerno YouTube Channel"
      target: "_blank"
  - link:
      icon: "fa-brands fa-tiktok"
      text: "TikTok <span class='link-button-text'>(Stream Highlights!)</span>"
      url: "https://www.tiktok.com/@ramenferno"
      alt: "RamenFerno TikTok Page"
      title: "RamenFerno TikTok Page"
      target: "_blank"
  - link:
      icon: "fa-brands fa-discord"
      text: "Discord <span class='link-button-text'>(Join the Emberpot!)</span>"
      url: "https://discord.gg/HrmQAEdTcV"
      alt: "Emberpot Discord Server"
      title: "Emberpot Discord Server"
      target: "_blank"
  - link:
      icon: "fa-brands fa-twitter"
      text: "Twitter <span class='link-button-text'>(üê•)</span>"
      url: "https://twitter.com/@ramenferno"
      alt: "RamenFerno Twitter Page"
      title: "RamenFerno Twitter Page"
      target: "_blank"
  - link:
      icon: "fa-brands fa-bluesky"
      text: "Bluesky"
      url: "https://bsky.app/profile/ramenferno.com"
      alt: "RamenFerno Bluesky Page"
      title: "RamenFerno Bluesky Page"
      target: "_blank"
  - link:
      icon: "fa-solid fa-heart"
      text: "VGen"
      url: "https://vsona.co/ferno"
      alt: "Ferno VSona Page"
      title: "RamenFerno VSona Page"
      target: "_blank"
  - link:
      icon: "fa-classic fa-gift"
      text: "Throne <span class='link-button-text'>(Thank you so much!)</span>"
      url: "https://throne.com/ramenferno"
      alt: "RamenFerno's Throne Wishlist"
      title: "RamenFerno's Throne Wishlist"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/RamenFerno"
      title: "RamenFerno GitHub Page"
      alt: "RamenFerno GitHub Page"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/ramenferno"
      title: "RamenFerno Instagram Page"
      alt: "RamenFerno Instagram Page"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:ramenferno@outlook.com"
      title: "Email: ramenferno@outlook.com"
      alt: "ramenferno@outlook.com"
      target: "_blank"

playlist: >
    <iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/playlist/54FLfyvWnC1Yec2ykuXzwB?utm_source=generator" width="100%" height="208" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

# Footer text
footer: |
    <div style="margin-top:2em;text-align:center">
        <h3><b>Credits</b></h3>
        <p>
            <a href="https://vgen.co/naraaastudio" target="_blank"><u><b>Naraaa</b></u></a><br>
            <a href="https://vgen.co/naraaastudio/portfolio/showcase/ramenferno-s-live2d-model/43047066-5386-49c3-8058-f45494d04ff1" target="_blank">Ferno model</a><br>
            Emberpot model
        </p><br>

        <p>
            <a href="https://vgen.co/patheaple" target="_blank"><u><b>Patt</b></u></a><br>
            <em>Signal Flare</em> cover art<br>
            <a href="https://vgen.co/patheaple/product/vtuber-base-body-model-rendered-not-rigged-/91ac2484-fa75-494f-8add-6670d099566f" target="_blank">VTuber Base</a> (used for concept art)
        </p><br>

        <p>
            <a href="https://vgen.co/Eruru" target="_blank"><u><b>Eruru</b></u></a><br>
            <a href="https://vgen.co/Eruru/service/neon-sign-signature-watermark/a491f9ee-b519-4be5-8f86-2da7253b54ac" target="_blank">Flaming Bowl logo</a>
        </p><br>

        <p>
            <a href="https://www.etsy.com/shop/milaeshop" target="_blank"><u><b>milaeshop</b></u></a><br>
            <a href="https://www.etsy.com/listing/4391673194/glowy-chat-widget-horizontal-and" target="_blank">Glowy chat widget</a>
        </p><br>

        <p>
            <a href="https://commons.wikimedia.org/wiki/User:Shisma" target="_blank"><u><b>Shisma</b></u></a><br>
            <a href="https://commons.wikimedia.org/wiki/File:Japanese_Wave_Pattern.svg" target="_blank">Japanese Wave Pattern</a>
            (<a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">License</a>)
        </p>
    </div>

# Footer copyright message
# Linkyee is a 100% free, open-source project‚Äîfeel free to modify the copyright message as you like. :)
copyright: >
  Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
